### ISSUE TITLE
Selection of categories in faceted search

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#1]
The faceted search should have the possibility to select/deselect all categories.

**Comment by strec** [comment]
Note: Talking about the "new search" (beta). In the results-page (widget "search2") there is the possibility to select categories in the sidebar. The aim is to be able to select/deselect all category checkboxes at once. When first returning the results, all categories are selected, because results from these categories have been found. Deselecting all category-checkboxes at once here makes it easier to narrow down the result to just a few categories:
So deselect all and then just select the ones I am interested in or select all and then remove the ones I don't want to be included in the search.
