### ISSUE TITLE
Fond metadata updates only saved when using actual server address in the backend

### ISSUE THREAD

**Issue by icarus-eu** [icaruseu/mom-ca#237]
When trying to save changes to fond metadata using the official url (for example http://monasterium.net/mom/CZ-NA/ACK/edit-fond), the user is presented with an error message stating `Error: Document could not be saved` ([screenshot](https://cloud.githubusercontent.com/assets/6792937/7135227/c954c9c8-e2a4-11e4-80e5-d334098b1a21.PNG)).

When using the server's main address (http://ftp.dioezesanarchiv.acw.at:8181/mom/CZ-NA/ACK/edit-fond), the changes are stored successfully.

**Comment by strec** [comment]
No surprise...
These eight lines of code literally give me the shivers!
https://github.com/icaruseu/mom-ca/blob/master/my/XRX/src/mom/app/fond/widget/edit-fond.widget.xml#L106
The servername must be obtained with $xrx:jetty-request-base-url
I strongly recommend to distrust the widget and what is underneath the hood, there.
Looking at the attempt to set $server twice (although it is not possible in XQuery because of the concept of immutability) and the overall way things have been done, I am truly surprised it has not flown apart earlier.
