### ISSUE TITLE
Phrase search in combination with archive constraint throws Java Error

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#352]
e.g. http://monasterium.net/mom/search?q=%22Papst+Gregor%22&sort=date&arch=AT-DOZA 
javax.servlet.ServletException: An error occurred: String index out of range: -64
    at org.exist.http.servlets.EXistServlet.doGet(EXistServlet.java:256)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)

**Comment by GVogeler** [comment]
@Strec berichtet: Eine Variante des Fehlers ist "Gregor X". Damit ändert sich der Fehlerwert auf -51.

**Comment by GVogeler** [comment]
Search with other archive works fine: http://monasterium.net/mom/search?q=%22Papst+Innozenz%22&sort=date&arch=AT-StiAGe
Also work with other term: http://monasterium.net/mom/search?q=%22Kaiser%20Friedrich%22&sort=date&arch=AT-DOZA
=> Problem realted to `"Gregor\s.*?|.*?\sGregor"` and AT-DOZA?

**Comment by StephanMa** [comment]
The problem is a subnode of cei:text. The generated Error is based on a lucene Error which can be thrown if there is any corrupted data in it. 

Changing the query from
`$context//cei:text[ft:query(./descendant-or-self::*,'", $search:q, "',$search:options)]`
to
`$context//cei:text[ft:query(.,'", $search:q, "',$search:options)]`

It should not make any speed difference because cei:text is already indexed. There is no need to query any desencandant nodes.

**Comment by StephanMa** [comment]
#44 has to be checked, if implementation still allows searching for attributes

**Comment by GVogeler** [comment]
#44 is probably affected by the change #429 : http://www.monasterium.net/mom/atom/GET/metadata.charter.public/AT-StiAH/HeiligenkreuzOCist/1228_IX_19.cei.xml contains "Papst Gregor IX. (1227-1241), Aussteller, Siegler" but http://www.monasterium.net/mom/search2?q=%22Papst+Gregor+IX.+%281227-1241%29Papst+Gregor+IX.+%281227-1241%29%2C+Aussteller%2C+Siegler%22&option=and&img=&annotations=&sort=date&categories=&context= does not return results.

**Comment by GVogeler** [comment]
see https://github.com/icaruseu/mom-ca/issues/44#issuecomment-99519944 on the problem

**Comment by StephanMa** [comment]
After some further investigations, i can say that the problem isn't mom-ca related.

e.g. see charter 

tag:www.monasterium.net,2011:/charter/AT-DOZA/Urkunden/127

in cei:sealDesc you can read:
"Bleibulle an rotgelben Seidenfäden 2) Erneuerung 1231 August 6. Anagni, durch Papst Gregor IX. (= Nr. 200) 3) Erneuerung 1231 September 15. Reate, durch Papst Gregor IX. (= Nr. 201) 4) Transsumpt 13170827. Köln (= Nr. 1389)."

The problem is, that the term "Erneuerung 1231" is a multiple entry in this string. So lucene becomes confused and returns an error.

I have made an Bugfix in the Lucene-Module in eXist-2.0.x. So i would suggest to implement the eXist-zip to our repo.

Suggestions?

**Comment by GVogeler** [comment]
The given examples work currently.
