### ISSUE TITLE
EditMOM3 has problems to deal with `&lt;`

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#353]
Editing http://monasterium.net/mom/AT-DOZA/Urkunden/385/charter or adding &lt; to a charter produces an "Error: failed to load save script"

**Comment by GVogeler** [comment]
see #291 for similar problems in VdUEdit

**Comment by StephanMa** [comment]
After some Minutes of Thinking, I am pretty sure that this is a "Won't fix". 

The Editor transforms the entire charter into a string. The tags are converted into a &lt; or a &gt; ! If you add a &lt; into a Textelement, there Save-Script will fail because of missing closing tag. I am pretty sure about it. 

It must be forbidden to use such a special Character inside the Editor. That's the only chance to avoid such a behavior.

**Comment by GVogeler** [comment]
I would expect the editor to mask the ampersand (&) as well, so that the
string ```&lt;``` would be handled as ```&amp;lt;``` in the JavaScript.

< is already filtered as a not allowed character.

Am 26.10.2015 um 16:58 schrieb Stephan M:

**Comment by StephanMa** [comment]
I checked this Issue directly on the monasterium.net-Server.
EditMOM3 saves all changes without any problems.

For me, there isn't any Problem. Maybe some Cache-Problems?

**Comment by StephanMa** [comment]
The Editor doesn't save the Charter if there are single special Characters, e.g. & inside a text.
If you're using html codes like &gt; or &lt; it works without problems.

**Comment by GVogeler** [comment]
solved with #521
