### ISSUE TITLE
EditMOM3: highlighting a word and typing to replace it creates an "Error: Failed to load save script"

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#371]
StephanMa: Schaut man sich die XML-Ansicht an, so stellt man fest, dass der komplette restliche XML-Baum nach Eingabe des ersten Buchstabes komplett  gelöscht worden ist: `<cei:bibl>Il documento occupa la parte i` Demnach haben wir hier wahrscheinlich ein jQuery/JS-Problem.

**Comment by StephanMa** [comment]
After some further review, i can confirm that the error is inside the XPath.js regarding the function [`ReplaceMixedSelection` ] (https://github.com/icaruseu/mom-ca/blob/master/my/XRX/res/jssaxparser/XPath.js#L418-Lundefined) .
I have to do some further analyzing of this section, because it isn't easy to debug.

**Comment by GVogeler** [comment]
solved with #375
