### ISSUE TITLE
Einbindung von Attributen in die Suche (@reg, @rend, @type, @lemma ...)

### ISSUE THREAD

**Issue by GVogeler** [icaruseu/mom-ca#44]
add these attributes to the Lucene index
check how search results (KWIC) display hits in the attributes

**Comment by strec** [comment]
" @reg, @rend, @type, @lemma ... "

-> does ... mean all possible attributes present in a cei document or a specific subset?
If a subset, which rule of determining which of them to include applies?

**Comment by GVogeler** [comment]
`@reg`, `@lemma`, `@sublemma`, `@corr`, `@sic`, `@class`, `@from`, `@to`, `@value`, `@reason`, `@hand`, `@function`, `@key`, `@abbr`, `@expan` is my suggestion.

**Comment by strec** [comment]
At the moment, in the search, there is a fulltext-search implemented on the cei:text element. The database-query-string (the construction of which can be found inside search.xqm and which later gets "evaluated" by util:eval function) looks like this, when searching for "Karner", e.g.:
```let $context := collection("/db/mom-data/metadata.charter.public/") for $charter in $context//cei:text[ft:query(.,'Karner',$search:options)] order by ($charter//cei:date/@value, $charter//cei:dateRange/@from, $charter//cei:dateRange/@to)[1] ascending  return $charter```
As seen by the first parameter inside ft:query, the context of the query is the current cei:text-node. Meaning that the string value of everything in it is searched. String value of cei:text means excluding the attributes, though. As far as I know, everything that is searched for in the current context needs to have been indexed inside the corresponding collection.xconf file beforehand. Taking only a look at the ft:query statement from above...:

[1.:] `ft:query(.,'Karner', $search:options)`
-> only containing the actual text and no attributes.

[2.:] `ft:query(./descendant-or-self::*,'Karner', $search:options)` 
-> also contains the full text search on attributes, because they are nodes, too.

[3.:] `ft:query(. | .//attribute::*,'Karner', $search:options)`
-> is a bad idea, because there is a huge performance hit.

Performance does not slow down remarkably, when using [2.:]
So [2.:] or similar is probably the way to go, here.

On the search-results page, KWIC just does not display anything, because attribute values are not included in the string, as described above, I guess.
KWIC produces errors in the context of displaying hits when they were found in the attributes. After searching, the results can be clicked on. The corresponding charter is linked and presented through the charter widget, when clicked on. The charter widget is informed about the right charter to display through the url path. And handed the search-term by url-parameter. In the above example by appending `?q=Karner`

Now the charter widget can't handle it, because it does not find the attribute-hit inside the string value of cei:text, I guess, because it does not look inside the attributes.
A mechanism has to be implemented to present the hit when in attribute, if KWIC is desired for attributes, too.

**Comment by GVogeler** [comment]
1. If it helps, you can use search2 as the main development basis for this feature (cfr. #177)
2. In general: finding something in the attributes is more important than not beeing able to display it in KWIC style
3. A general move to replace these attributes with explicit elements can be considered if that seems to be the cleanest solution.
4. A KWIC display of the result list including attributes should be possible to write in XQuery, because the list already contains only text fragments. In the single charter view some attributes are not included.
Currently I would suggest solution 2 if solution 4 is too time consuming.

**Comment by strec** [comment]
Alright. Solution 2 is already done. search & search2 work. I am sitting at solution 4 at the moment. And it is a little time consuming. kwic does not support attributes by default...

**Comment by GVogeler** [comment]
I opend #257 for the further discussion - that we can close this issue with the appropriate pull request.

**Comment by GVogeler** [comment]
Just to be sure everything is working correctly here my "unit test":
http://monasterium.net/mom/AT-StiAA/Urkunden/1144_VII_25/charter contains `<cei:persName reg="Almar von Frankenreith, Zeuge">Almar de Franchenrouthe</cei:persName>`. I would expect that http://monasterium.net/mom/search?q=Almar+von+Frankenreith&sort=date&arch= and http://monasterium.net/mom/search2?q=Almar+von+Frankenreith&option=and&img=&annotations=&sort=date&categories=&context= would find this charter, but both show no results. Is this a consequence of the KWIC issue #257 ?

**Comment by strec** [comment]
Have you done
ant deploy-exist-xconf
and
reindexed the collection?
